version: '3.5'

services:
  api:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0
